### ISSUE TITLE
Manage conversation history 

### ISSUE THREAD

**Issue by sabbadino** [MicrosoftDocs/semantic-kernel-docs#103]
Hi, is there any built-in functionality to have semantic kernel manage the conversation history (such as I pass last user prompt and a conversation I'd), or I have to manage it outside of the kernel ?
Thanks

**Comment by moonbox3** [comment]
Hi @sabbadino,

Thanks for reaching out! The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo [link to main repo]? That way, it will get the attention it needs.

Thanks for understanding!
