### ISSUE TITLE
Improve getting started docs for Copilot chat

### ISSUE THREAD

**Issue by matthewbolanos** [MicrosoftDocs/semantic-kernel-docs#22]
Need to create documentation to address the issues noted here: [Improve the getting started documentation for Copilot chat#1352](https://github.com/microsoft/semantic-kernel/issues/1352)

**Comment by securigy** [comment]
It is not only Pinecone issue. Exactly the same exception on the same line happens for qdrant.

**Comment by crickman** [comment]
Copilot Chat is retired
