### ISSUE TITLE
Samples issue - Dotnet  sample 4 not working

### ISSUE THREAD

**Issue by Escoto** [MicrosoftDocs/semantic-kernel-docs#24]
Hi! I am testing the samples. 

I tested all of them (the dotnet version) using `AzureOpenAI`. They all worked except the 4th. I don't get any Erros, just no answer. This is the generated plan:
`{
  "state": [
    {
      "Key": "INPUT",
      "Value": ""
    }
  ],
  "steps": [],
  "parameters": [
    {
      "Key": "INPUT",
      "Value": ""
    }
  ],
  "outputs": [],
  "next_step_index": 0,
  "name": "",
  "skill_name": "Microsoft.SemanticKernel.Planning.Plan",
  "description": "I have $2130.23. How much would I have after it grew by 24% and after I spent $5 on a latte?"
}`

I tested with different models, and endpoint types but couldn't make it work. 

I don't have access to `text-davinci-003`, I am wondering if I need this specific model?

**Comment by moonbox3** [comment]
Hi @Escoto,

Do you still need help with this issue? The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo? That way, it will get the attention it needs.

Thanks for understanding!
