### ISSUE TITLE
Problem with creating semantic functions inline...

### ISSUE THREAD

**Issue by sramaswami11** [MicrosoftDocs/semantic-kernel-docs#53]
Please refer to the document at the following url:
https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/plugins/semantic-functions/inline-semantic-functions?tabs=Csharp

When I am trying to create a semantic function inline, the code given in the documentation url above does not work:
Specifically, in the following code:
var promptConfig = new PromptTemplateConfig
{
    Schema = 1,
    Type = "completion",
    Description = "Gets the intent of the user.",
    Completion =
    {
        MaxTokens = 500,
        Temperature = 0.0,
        TopP = 0.0,
        PresencePenalty = 0.0,
        FrequencyPenalty = 0.0
     },
    Input =
     {
        Parameters = new List<InputParameter>
        {
            new InputParameter
            {
                Name = "input",
                Description = "The user's request.",
                DefaultValue = ""
            }
        }
    }
};

I get syntax errors for the following : MaxTokens, Temperature, TopP, PresencePenalty, FrequencyPenalty

Error	CS0117	'AIRequestSettings' does not contain a definition for 'MaxTokens'  etc...

I am using   microsoft.semantickernel\1.0.0-beta2\

**Comment by crickman** [comment]
https://github.com/microsoft/semantic-kernel/issues/3173

**Comment by sramaswami11** [comment]
Thanks for the response Chris, I will try that later.  BTWI was also trying to use the code in the docs where context parameters are used to pass multiple inputs as shown in the url below:
https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/plugins/native-functions/multiple-parameters?tabs=Csharp
and I am running into syntax errors related to SKParameter not being recognized, the error is:

Error	CS0246	The type or namespace name 'SKParameter' could not be found (are you missing a using directive or an assembly reference?)	SKPrompts	C:\Siva\Projects\SemanticKernel\SKPrompts\SKPrompts\Plugins\MathPlugin\Math.cs	19	Active
Lemme know if you need me to create a separate issue for this.

Thanks

**Comment by crickman** [comment]
Beta3 is available: https://github.com/microsoft/semantic-kernel/releases/tag/dotnet-1.0.0-beta3

**Comment by sramaswami11** [comment]
Just curious, is semantic kernel going to GA status in November with the
release of .net 8.0?
Thanks

**Comment by moonbox3** [comment]
Do you still need help with your issue? The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo? That way, it will get the attention it needs.

Thanks for understanding!
