### ISSUE TITLE
Can I pass more than one variable to a plugin call when using the prompt template syntax?

### ISSUE THREAD

**Issue by Cotspheer** [MicrosoftDocs/semantic-kernel-docs#65]
It is unclear from the docs if I can pass only a default parameter "input" or if I can pass additionally variables if I know the plugin accepts those. [prompt-template-syntax#function-parameters](https://learn.microsoft.com/en-us/semantic-kernel/prompt-engineering/prompt-template-syntax#function-parameters). For example I have a plugin that accepts a mandatory input and can accept additional metadata treated differently. Am I able to call the plugin like this: 

```text 
The weather today in {{$city}} is {{weather.getForecast $city $temperatureUnit}}.
```
where temperatureUnit can be Fahrenheit or Celsius.

It would be good to clarify that behavior and if it is possible to add another example.

EDIT: According to [multiple-parameters](https://learn.microsoft.com/en-us/semantic-kernel/ai-orchestration/plugins/native-functions/multiple-parameters?tabs=Csharp)  it seems to be supported in code but it isn't clear for the template syntax.

**Comment by trt** [comment]
Hi @Cotspheer, I agree it's not straightforward from docs how to handle multiple parameters. I think this [docs section](https://learn.microsoft.com/en-gb/semantic-kernel/ai-orchestration/plugins/semantic-functions/templatizing-semantic-functions?tabs=Csharp#adding-variables-to-the-prompt) might help you a bit.

**Comment by Cotspheer** [comment]
Syntax changed with handlebars templates, closing therefore my issue.
