### ISSUE TITLE
cannot import name 'sk_function' from 'semantic_kernel.plugin_definition'

### ISSUE THREAD

**Issue by skim0011** [MicrosoftDocs/semantic-kernel-docs#85]
I'm following this post below and getting the error in the screenshot.

python=3.9
semantic-kernel=0.5.1.dev0

https://learn.microsoft.com/en-us/semantic-kernel/agents/planners/evaluate-and-deploy-planners/create-a-prompt-flow-with-semantic-kernel

![image](https://github.com/MicrosoftDocs/semantic-kernel-docs/assets/156260712/db013248-a8b3-4c75-bd18-c758dd6f500e)

Any idea where I can start investigate from?

**Comment by y00281951** [comment]
i have the same problem

**Comment by y00281951** [comment]
change sk_function to kernel_function, i find that the sample code is not update

**Comment by moonbox3** [comment]
Hi @y00281951 are you still having an issue? If so, the repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo? That way, it will get the attention it needs.

Thanks for understanding!
