### ISSUE TITLE
Error when using Semantic Kernel Plugin

### ISSUE THREAD

**Issue by YashTrivedi21** [MicrosoftDocs/semantic-kernel-docs#86]
I am trying to run and check the sample codebase provided by the semantic Kernel repo in samples\dotnet\14-Create-ChatGPT-Plugin. I tried running their sk-chatgpt-azure-functions project but it threw an error related to semantic-functions-generator. As seen in the image below, that project can't be loaded due to some reason, I tried reloading multiple times.
![Picture1](https://github.com/MicrosoftDocs/semantic-kernel-docs/assets/62197105/db3e14c8-55c5-49ca-a9c2-1501554075e1)

So I tried to add it manually and create the same folder structure and code as was given on their Github page. Then I tried running the code which is used to test this plugin, but there I got this error while running:
![Picture2](https://github.com/MicrosoftDocs/semantic-kernel-docs/assets/62197105/5f19157e-ad2d-4a80-8de3-ce04ebb49677)

Not sure what the error means since I couldn't find anything related to this online.
Any help would be appreciated. Thanks!

**Comment by moonbox3** [comment]
Thanks for reaching out! The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo [link to main repo]? That way, it will get the attention it needs.

Thanks for understanding!
