### ISSUE TITLE
is python ollama test ok?

### ISSUE THREAD

**Issue by y00281951** [MicrosoftDocs/semantic-kernel-docs#89]
i try to use ollma llama2 to test 11-planer, but get errs, i dont know if python ollama is ready to use

**Comment by y00281951** [comment]
@juliomenendez

**Comment by moonbox3** [comment]
Thanks for reaching out! The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo [link to main repo]? That way, it will get the attention it needs.

Thanks for understanding!
