### ISSUE TITLE
AutoInvokeKernelFunctions arent invoking

### ISSUE THREAD

**Issue by kgrosvenor** [MicrosoftDocs/semantic-kernel-docs#97]
When i use the example from microsoft learn about AutoInvokeKernelFunctions, when i look at the history response i can see that ToolCalls are passing arguments as code rather then properly invoking the functions for example:

If i have a MathPlugin, and ask for 2 * 5, in the arguments it passes code as if the plugin was describing how to use a SDK..., how can you tell the model to not do this? 

Have provided a screenshot of the output, you can see it is generating incorrect text for the time plugin,

It should be passing as 

name: 'Prompt-TimePlugin',
arguments: {...}

**Comment by kgrosvenor** [comment]
![image](https://github.com/MicrosoftDocs/semantic-kernel-docs/assets/4264887/cafaf464-27ad-4d54-9e68-a127fb5b00cb)

**Comment by moonbox3** [comment]
Thanks for reaching out! The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo [link to main repo]? That way, it will get the attention it needs.

Thanks for understanding!
