### ISSUE TITLE
How to evaluate Semantic -Kernel planner and Plugins without using prompt flow ? 

### ISSUE THREAD

**Issue by Coding-With-Ashish** [MicrosoftDocs/semantic-kernel-docs#98]
We have integrated semantic kernel with GPT4 to interact with a C# .NET application. At present, Prompt flow does not support C# language, but we still want to test LLM response. Is there any way we can do this without using prompt flow ?

**Comment by moonbox3** [comment]
Thanks for reaching out! The repo where you've posted isn't monitored as frequently. Could you please post your question as an [issue](https://github.com/microsoft/semantic-kernel/issues/new/choose) or start a [discussion](https://github.com/microsoft/semantic-kernel/discussions/new/choose) in our main repo [link to main repo]? That way, it will get the attention it needs.

Thanks for understanding!
